spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/gram__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: qkr96#
  config:
    import: "classpath:base.yml"
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com # 사용하는 SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username: # 발신자 계정 이메일
    password: # 발신자 계정 비밀번호
    properties:
      mail.smtp.auth: true # 인증 사용 여부
      mail.smtp.starttls.enable: true # TLS 사용 여부
      mail.smtp.starttls.required: true # TLS 필수 여부
logging:
  level:
    root: INFO
    com.ll.gramgram_ai: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
custom:
  registration:
    limit: 10
